spring:
  application:
    name: concert
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/concert
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true         # 쿼리를 표준 출력으로
    properties:
      hibernate:
        format_sql: false  # 아름답게 출력
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always