name: Dev CI/CD Pipeline

# push, pull request시에 github action 실행
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set YML
        run: |
             cd ./week3
             mkdir -p src/main/resources
             echo "${{ secrets.APPLICATION_DEV_YML }}" | base64 --decode > src/main/resources/application.yml
             find src

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Permission go Gradlew
        run : |
              cd ./week3
              chmod +x ./gradlew

      - name: Build with Gradle
        run: |
             cd ./week3
             ./gradlew build
             
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image and Push
        env:
          NAME: ${{ secrets.DOCKERHUB_NAME }}
          REPO: ${{ secrets.DOCKERHUB_REPO_NAME }}
        run: |
             cd ./week3
             docker build -t "${{ env.NAME }}/${{ env.REPO }}:latest" -f Dockerfile .
             docker push "${{ env.NAME }}/${{ env.REPO }}:latest"
             
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-region: ${{ secrets.AWS_REGION }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login AWS ECR service
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
