name: PullRequest CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set YML
        run: |
          cd ./week3
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-


      - name: Permission go Gradlew
        run : |
              cd ./week3
              chmod +x ./gradlew

      - name: Build with Gradle
        run: |
             cd ./week3
             ./gradlew test
